name: SurvivalAnalysisPython
channels:
- conda-forge
- defaults
dependencies:
  - python=3.7
  - jupyter
  - numpy
  - scipy
  - pandas
  - lifelines
  - pytables
  - matplotlib
  - seaborn
  - tabula-py
  - wget
  - pip
  - pip:
    - empyrical-dist




