name: SurvivalAnalysisPython
channels:
- conda-forge
- defaults
dependencies:
  - python=3.7
  - jupyter
  - numpy
  - scipy>=1.2
  - pandas
  - lifelines>=0.23
  - pytables
  - matplotlib
  - seaborn
  - tabula-py
  - wget
  - pip
  - pip:
    - empiricaldist
